spring:
  application:
    name: zmessenger
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  redis:
    host: "localhost"
    port: "6379"
    password: "Amkalultras1"
    url: redis://Amkalultras1@127.0.0.1:6379
    timeout: 2000
    ssl: true
    lettuce:
      pool:
        size: 10
        max-idle: 8
        min-idle: 2